CREATE TABLE EMPLOYEE (
    CODE VARCHAR(4),
    NAME CHAR(30),
    DOB DATE NOT NULL,
    DESIGNATION CHAR(20),
    SALARY INT
     );


 INSERT INTO EMPLOYEE(CODE,NAME,DOB,DESIGNATION,SALARY)
   VALUES ('E001','SARA','1992-04-02','MANAGER',60000),
   ('E002','WILLIAMS','1994-12-14','CLERK',27000),
    ('E003','DOE','1998-12-14','ACCOUNTANT',30000);

 DELIMITER $$
 CREATE TRIGGER PREVENT_INSERTION
    BEFORE INSERT ON EMPLOYEE
     FOR EACH ROW
     BEGIN
     IF (CURRENT_TIME() BETWEEN '17:00' AND '00:00' ) THEN
     SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'NO CHANGES TO EMPLOYEE TABLE';
     END IF;
     END $$

 DELIMITER ;
 
 
 DELIMITER $$
 CREATE TRIGGER PREVENT_UPDATION
     BEFORE UPDATE ON EMPLOYEE
     FOR EACH ROW
     BEGIN
     IF (CURRENT_TIME() BETWEEN '17:00' AND '00:00' ) THEN
     SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'NO CHANGES TO EMPLOYEE TABLE';
     END IF;
    END $$


 DELIMITER ;
 
 
 DELIMITER $$
 CREATE TRIGGER PREVENT_DELETION
     BEFORE DELETE ON EMPLOYEE
     FOR EACH ROW
     BEGIN
    IF (CURRENT_TIME() BETWEEN '17:00' AND '00:00' ) THEN
    SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'NO CHANGES TO EMPLOYEE TABLE';
     END IF;
     END $$


 DELIMITER ;
